- name: install git from apt
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: yes
  with_items:
    - git
    - gitk
    - git-gui
    - meld

- name: configure git
  template: 
    src: user_gitconfig
    dest: ~/.gitconfig
